resources:
  - name: ${_MICROSERVICE}-cloudbuild-deploy-python
    type: gcp-types/cloudbuild-v1
    properties:
      steps:
        - id: test-unit
          name: gcr.io/${PROJECT_ID}/pipenv
          args:
            - python -m unittest
            - microservices/${_MICROSERVICE}/**/tests.py
        - id: prepare
          name: gcr.io/${PROJECT_ID}/pipenv
          entrypoint: bash
          args:
            - -c
            - |
              pipenv lock -r > requirements.txt
              cp requirements.txt microservices/${_MICROSERVICE}/
        - id: artifact
          name: gcr.io/${PROJECT_ID}/artifact-uploader
          entrypoint: bash
          args:
            - -c
            - |
              cd microservices/${_MICROSERVICE}/
              zip -r /tmp/${_MICROSERVICE}.zip .
              gsutil cp /tmp/${_MICROSERVICE}.zip gs://${_ARTIFACTS_BUCKET}/
        - id: deploy
          name: gcr.io/cloud-builders/gcloud
          args:
            - deployment-manager
            - deployments update
            - ${_MICROSERVICE}-runtime
            - --config=microservices/${_MICROSERVICE}/infrastructure/runtime/runtime.yml
