imports:
  - path: https://raw.githubusercontent.com/GoogleCloudPlatform/cloud-foundation-toolkit/v0.3.4/dm/templates/cloudbuild/cloudbuild.py
    name: cloudbuild

resources:
  - name: ${_MICROSERVICE}-cloudbuild-deploy-python
    type: cloudbuild
    properties:
      steps:
        - id: test-unit
          name: gcr.io/${PROJECT_ID}/pipenv
          args:
            - python -m unittest
            - microservices/${_MICROSERVICE}/**/tests.py
        - id: artifact
          name: gcr.io/${PROJECT_ID}/cloud-sdk
          entrypoint: bash
          args:
            - -c
            - |
              cp Pipfile* microservices/${_MICROSERVICE}/
              tar czvf /tmp/${_MICROSERVICE}.tar.gz microservices/${_MICROSERVICE}/
              gsutil cp /tmp/${_MICROSERVICE}.tar.gz gs://{{ properties['artifactBucket'] }}/
        - id: deploy
          name: gcr.io/cloud-builders/gcloud
          args:
            - deployment-manager
            - deployments update
            - ${_MICROSERVICE}-microservice
            - --template=microservices/${_MICROSERVICE}/infrastructure/runtime/index.jinja
            - --properties=artifactsBucket:${_ARTIFACTS_BUCKET}